x-common: &common-setup
  network_mode: host
  privileged: true
  volumes:
    - ${HOME}/.Xauthority:/home/mobile/.Xauthority:rw
    - .:/home/mobile/ros2_ws/src:rw
    - /tmp/.X11-unix:/tmp/.X11-unix:rw
    - /dev/dri:/dev/dri:rw
    - /run/user/1000/pulse:/run/user/1000/pulse
    - /dev/v4l:/dev/v4l:ro
  environment:
    - NVIDIA_VISIBLE_DEVICES=all
    - NVIDIA_DRIVER_CAPABILITIES=compute,utility,video,graphics,display
    - DISPLAY
    - QT_X11_NO_MITSHM=1
    - PULSE_SERVER=unix:/run/user/1000/pulse/native
  working_dir: /home/mobile/ros2_ws

services:
  terminal:
    <<: *common-setup
    image: fabook/cv:v0.0.5
    stdin_open: true
    tty: true
    gpus: all
    runtime: nvidia
    devices:
      - /dev/bus/usb:/dev/bus/usb
      - /dev/video0:/dev/video0
      - /dev/video1:/dev/video1
      - /dev/snd:/dev/snd
    group_add:
      - "video"
      - "44"
    command: [
      "/bin/bash","-lc","
      sudo chmod 666 /dev/ttyUSB* 2>/dev/null || true &&
      sudo chmod 666 /dev/spidev* 2>/dev/null || true &&
      sudo chmod 666 /dev/ttyACM* 2>/dev/null || true;
      exec bash"
      ]

  rest_api:
    <<: *common-setup
    build: .
    image: robot-assistants-rest-api:dev
    profiles: ["api"]
    stdin_open: true
    tty: true
    gpus: all
    runtime: nvidia
    devices:
      - /dev/bus/usb:/dev/bus/usb
      - /dev/video0:/dev/video0
      - /dev/video1:/dev/video1
      - /dev/snd:/dev/snd
    group_add:
      - "video"
      - "44"
    command: [
      "/bin/bash","-lc",
      "source /opt/ros/humble/setup.bash && python3 -m pip install -r src/iros_rest_api/requirements.txt && colcon build --symlink-install --packages-select iros_custom_msgs iros_rest_api && source install/setup.bash && ros2 run iros_rest_api api_server --host 0.0.0.0 --port 8000"
    ]
